### ISSUE TITLE
[NovDaejon Seminar] 이미지 깨짐

### ISSUE THREAD

**Issue by Dry8r3aD** [ubuntu-kr/events#2]
![sc_ 2017-10-16 02 13 18](https://user-images.githubusercontent.com/5144422/31587172-ba4d7fac-b217-11e7-9cfc-c505774a9a2a.png)

두번째 연사분 사진 깨짐

**Comment by sukso96100** [comment]
저는 잘 나오는 것 같습니다만...
<img width="1440" alt="2017-10-16 8 44 56" src="https://user-images.githubusercontent.com/1916739/31590632-899892b6-b24e-11e7-8b2a-257bd2289dd0.png">

**Comment by sukso96100** [comment]
![2017-10-16 10 09 09](https://user-images.githubusercontent.com/1916739/31591382-1a8ca6f8-b25a-11e7-87d8-0bf030d0b557.png)
크롬에선 잘 나오는데 사파리에서 나오오질 않는군요.

**Comment by sukso96100** [comment]
이미지 포멧이 구글 자체 포멧이여서 그런가 보네요

**Comment by sukso96100** [comment]
음... 걍 못불러오네요 URL 고쳐도

**Comment by sukso96100** [comment]
사파리 에서도 로드 되는 URL 을 찾았습니다. 이슈를 닫습니다.
